import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/lib/supabase/types";

// Data assembly for the Export endpoint (issue #29). Kept out of the route
// handler itself (src/app/api/export/route.ts) per the issue's own
// Constraints -- same "query/assembly logic lives in lib/queries, the route
// stays thin" split every other lib/queries module already follows.
//
// Every read below is explicitly scoped with `.eq("user_id", user.id)` (or,
// for list_items which has no user_id column of its own, indirectly via
// list_id IN <the caller's own list ids>) rather than relying on RLS alone --
// same convention as lib/queries/trash.ts and lib/queries/lists.ts.
//
// Unlike most other lib/queries functions, query errors here are thrown
// rather than swallowed into an empty/degraded result: those other reads
// back a page render, where an empty state is a reasonable fallback for a
// transient error; this one backs a downloadable "this is my whole library"
// file, where silently producing an incomplete export would be worse than
// the request failing outright. The route handler turns a thrown error into
// a 500.

type ItemStatus = Database["public"]["Enums"]["item_status"];
type PriorityLevel = Database["public"]["Enums"]["priority_level"];

export interface ExportSubtype {
  name: string;
  is_custom: boolean;
}

export interface ExportTag {
  name: string;
  is_custom: boolean;
}

export interface ExportLink {
  url: string;
  label: string | null;
}

export interface ExportImage {
  storage_path: string;
  is_cover: boolean;
  sort_order: number;
  created_at: string;
}

export interface ExportAttachment {
  filename: string;
  mime_type: string;
  size_bytes: number;
  created_at: string;
}

export interface ExportItem {
  id: string;
  title: string;
  category: string;
  subtype: ExportSubtype;
  status: ItemStatus;
  priority: PriorityLevel | null;
  rating: number | null;
  notes: string | null;
  review: string | null;
  created_at: string;
  updated_at: string;
  completed_at: string | null;
  tags: ExportTag[];
  links: ExportLink[];
  images: ExportImage[];
  attachments: ExportAttachment[];
}

export interface ExportList {
  name: string;
  created_at: string;
  // Each id matches an ExportItem.id present elsewhere in this same export --
  // a list_items row pointing at a trashed (and therefore excluded) item is
  // dropped below, never left dangling (mirrors getLists'/getListDetail's
  // existing "a list_items row for a trashed item still exists but never
  // counts/displays" behavior, lib/queries/lists.ts).
  item_ids: string[];
}

export interface ExportData {
  schema_version: 1;
  exported_at: string;
  items: ExportItem[];
  lists: ExportList[];
}

// Returns `null` only when there's no signed-in user -- the route handler's
// cue to respond 401 with no library data in the body. A query-level error
// throws (see header comment) rather than degrading to a partial export.
export async function buildExportData(): Promise<ExportData | null> {
  const supabase = await createClient();

  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) return null;

  const { data: itemRows, error: itemsError } = await supabase
    .from("items")
    .select(
      `
      id,
      title,
      status,
      priority,
      rating,
      notes,
      review,
      created_at,
      updated_at,
      completed_at,
      categories ( slug ),
      subtypes ( name, user_id ),
      item_tags ( tags ( name, user_id ) ),
      item_links ( url, label, created_at ),
      item_images ( storage_path, is_cover, sort_order, created_at ),
      item_attachments ( filename, mime_type, size_bytes, created_at )
    `,
    )
    .eq("user_id", user.id)
    .is("deleted_at", null)
    // Deterministic top-level order; not itself an acceptance criterion.
    .order("created_at", { ascending: true })
    // item_links must serialize in created_at order (issue #29 AC).
    .order("created_at", { referencedTable: "item_links", ascending: true })
    // item_images has no ordering requirement in the issue (V1 ever writes
    // one row, the cover) -- ordered anyway for determinism/future-proofing.
    .order("sort_order", { referencedTable: "item_images", ascending: true });

  if (itemsError) {
    throw new Error(`Failed to load items for export: ${itemsError.message}`);
  }

  const items: ExportItem[] = (itemRows ?? []).map((row) => {
    // Defensive embedded-resource normalization, same reasoning as every
    // other lib/queries module -- this project's types.ts is generated by a
    // fallback tool (see its header comment), not the literal
    // `supabase gen types` CLI.
    const category = Array.isArray(row.categories) ? row.categories[0] : row.categories;
    const subtype = Array.isArray(row.subtypes) ? row.subtypes[0] : row.subtypes;
    const tagRows = Array.isArray(row.item_tags) ? row.item_tags : [];
    const linkRows = Array.isArray(row.item_links) ? row.item_links : [];
    const imageRows = Array.isArray(row.item_images) ? row.item_images : [];
    const attachmentRows = Array.isArray(row.item_attachments) ? row.item_attachments : [];

    // is_custom for both subtype and tag is derived from `user_id IS NOT
    // NULL` on the specific source row (issue #29 AC) -- a predefined row
    // always has `user_id: null`, a caller-created one always carries their
    // own id (never another user's, per RLS).
    const tags: ExportTag[] = tagRows
      .map((itemTag) => {
        const tag = Array.isArray(itemTag.tags) ? itemTag.tags[0] : itemTag.tags;
        return tag ? { name: tag.name, is_custom: tag.user_id !== null } : null;
      })
      .filter((tag): tag is ExportTag => tag !== null);

    return {
      id: row.id,
      title: row.title,
      category: category?.slug ?? "",
      subtype: { name: subtype?.name ?? "", is_custom: (subtype?.user_id ?? null) !== null },
      status: row.status,
      priority: row.priority,
      rating: row.rating,
      notes: row.notes,
      review: row.review,
      created_at: row.created_at,
      updated_at: row.updated_at,
      completed_at: row.completed_at,
      tags,
      links: linkRows.map((link) => ({ url: link.url, label: link.label })),
      images: imageRows.map((image) => ({
        storage_path: image.storage_path,
        is_cover: image.is_cover,
        sort_order: image.sort_order,
        created_at: image.created_at,
      })),
      // Deliberately no storage_path here -- unlike images, attachment file
      // bytes are never recoverable from metadata alone (issue #29 AC).
      attachments: attachmentRows.map((attachment) => ({
        filename: attachment.filename,
        mime_type: attachment.mime_type,
        size_bytes: attachment.size_bytes,
        created_at: attachment.created_at,
      })),
    };
  });

  // The set of ids that actually made it into this export (i.e. owned,
  // non-trashed) -- used below to drop any list membership pointing at an
  // item that didn't.
  const includedItemIds = new Set(items.map((item) => item.id));

  const { data: listRows, error: listsError } = await supabase
    .from("lists")
    .select("id, name, created_at")
    .eq("user_id", user.id)
    .order("created_at", { ascending: true });

  if (listsError) {
    throw new Error(`Failed to load lists for export: ${listsError.message}`);
  }

  const listIds = (listRows ?? []).map((list) => list.id);

  // list_items has no user_id column of its own -- ownership is scoped
  // indirectly via list_id IN <the caller's own list ids> above, same
  // pattern getLists' count query (lib/queries/lists.ts) already uses.
  let memberRows: { list_id: string; item_id: string }[] = [];
  if (listIds.length > 0) {
    const { data, error: memberError } = await supabase
      .from("list_items")
      .select("list_id, item_id")
      .in("list_id", listIds)
      .order("sort_order", { ascending: true });

    if (memberError) {
      throw new Error(`Failed to load list memberships for export: ${memberError.message}`);
    }
    memberRows = data ?? [];
  }

  const itemIdsByList = new Map<string, string[]>();
  for (const row of memberRows) {
    // A list_items row for a trashed (excluded) item still exists in the
    // database but is silently dropped here -- never left dangling in the
    // export (issue #29 AC).
    if (!includedItemIds.has(row.item_id)) continue;
    const existing = itemIdsByList.get(row.list_id) ?? [];
    existing.push(row.item_id);
    itemIdsByList.set(row.list_id, existing);
  }

  const lists: ExportList[] = (listRows ?? []).map((list) => ({
    name: list.name,
    created_at: list.created_at,
    item_ids: itemIdsByList.get(list.id) ?? [],
  }));

  return {
    schema_version: 1,
    exported_at: new Date().toISOString(),
    items,
    lists,
  };
}
