import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/lib/supabase/types";

// Reusable read query (issue #12), added alongside categories.ts rather than
// overloading it per the issue's own file constraints. Fetches every
// non-deleted item the signed-in user owns in one category, ordered
// created_at desc (fixed order -- user-controlled sorting is #24). RLS on
// `items` already scopes reads to `auth.uid()` (database-schema.md §4), so
// no explicit user_id filter is needed here.

type ItemStatus = Database["public"]["Enums"]["item_status"];
type PriorityLevel = Database["public"]["Enums"]["priority_level"];

export interface LibraryItem {
  id: string;
  title: string;
  status: ItemStatus;
  rating: number | null;
  priority: PriorityLevel | null;
  subtypeName: string;
  tags: string[];
  coverUrl: string | null;
}

// Signed URLs are resolved per request rather than cached -- the `covers`
// bucket is private/path-scoped (database-schema.md §7), so getPublicUrl()
// is never used. 1 hour comfortably outlives a single page render/request.
const COVER_SIGNED_URL_TTL_SECONDS = 60 * 60;

export async function getLibraryItems(categoryId: string): Promise<LibraryItem[]> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("items")
    .select(
      `
      id,
      title,
      status,
      rating,
      priority,
      subtypes ( name ),
      item_tags ( tags ( name ) ),
      item_images ( storage_path, is_cover )
    `,
    )
    .eq("category_id", categoryId)
    .is("deleted_at", null)
    .order("created_at", { ascending: false });

  if (error) {
    // Swallowed rather than thrown, same convention as getCategories: a
    // library page that renders empty because of a transient read error is
    // better than one that crashes outright.
    console.error("Failed to load items:", error.message);
    return [];
  }

  return Promise.all(
    (data ?? []).map(async (row) => {
      // Nested embedded-resource shape depends on FK cardinality
      // (belongs-to -> object, has-many -> array); normalized defensively
      // here since this project's types.ts is generated by a fallback tool
      // (see its header comment), not the literal `supabase gen types` CLI.
      const subtype = Array.isArray(row.subtypes) ? row.subtypes[0] : row.subtypes;
      const images = Array.isArray(row.item_images) ? row.item_images : [];
      const coverImage = images.find((image) => image.is_cover);

      let coverUrl: string | null = null;
      if (coverImage) {
        const { data: signed } = await supabase.storage
          .from("covers")
          .createSignedUrl(coverImage.storage_path, COVER_SIGNED_URL_TTL_SECONDS);
        coverUrl = signed?.signedUrl ?? null;
      }

      const tagRows = Array.isArray(row.item_tags) ? row.item_tags : [];
      const tags = tagRows
        .map((itemTag) => {
          const tag = Array.isArray(itemTag.tags) ? itemTag.tags[0] : itemTag.tags;
          return tag?.name ?? null;
        })
        .filter((name): name is string => name !== null);

      return {
        id: row.id,
        title: row.title,
        status: row.status,
        rating: row.rating,
        priority: row.priority,
        subtypeName: subtype?.name ?? "",
        tags,
        coverUrl,
      };
    }),
  );
}
