import { createClient } from "@/lib/supabase/server";
import type { Database } from "@/lib/supabase/types";

// Reusable read query (issue #12), added alongside categories.ts rather than
// overloading it per the issue's own file constraints. Fetches every
// non-deleted item the signed-in user owns in one category, ordered
// created_at desc (fixed order -- user-controlled sorting is #24). RLS on
// `items` already scopes reads to `auth.uid()` (database-schema.md §4), so
// no explicit user_id filter is needed here.

type ItemStatus = Database["public"]["Enums"]["item_status"];
type PriorityLevel = Database["public"]["Enums"]["priority_level"];

export interface LibraryItem {
  id: string;
  title: string;
  status: ItemStatus;
  rating: number | null;
  priority: PriorityLevel | null;
  subtypeName: string;
  tags: string[];
  coverUrl: string | null;
}

// Signed URLs are resolved per request rather than cached -- the `covers`
// bucket is private/path-scoped (database-schema.md §7), so getPublicUrl()
// is never used. 1 hour comfortably outlives a single page render/request.
const COVER_SIGNED_URL_TTL_SECONDS = 60 * 60;

export async function getLibraryItems(categoryId: string): Promise<LibraryItem[]> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("items")
    .select(
      `
      id,
      title,
      status,
      rating,
      priority,
      subtypes ( name ),
      item_tags ( tags ( name ) ),
      item_images ( storage_path, is_cover )
    `,
    )
    .eq("category_id", categoryId)
    .is("deleted_at", null)
    .order("created_at", { ascending: false });

  if (error) {
    // Swallowed rather than thrown, same convention as getCategories: a
    // library page that renders empty because of a transient read error is
    // better than one that crashes outright.
    console.error("Failed to load items:", error.message);
    return [];
  }

  return Promise.all(
    (data ?? []).map(async (row) => {
      // Nested embedded-resource shape depends on FK cardinality
      // (belongs-to -> object, has-many -> array); normalized defensively
      // here since this project's types.ts is generated by a fallback tool
      // (see its header comment), not the literal `supabase gen types` CLI.
      const subtype = Array.isArray(row.subtypes) ? row.subtypes[0] : row.subtypes;
      const images = Array.isArray(row.item_images) ? row.item_images : [];
      const coverImage = images.find((image) => image.is_cover);

      let coverUrl: string | null = null;
      if (coverImage) {
        const { data: signed } = await supabase.storage
          .from("covers")
          .createSignedUrl(coverImage.storage_path, COVER_SIGNED_URL_TTL_SECONDS);
        coverUrl = signed?.signedUrl ?? null;
      }

      const tagRows = Array.isArray(row.item_tags) ? row.item_tags : [];
      const tags = tagRows
        .map((itemTag) => {
          const tag = Array.isArray(itemTag.tags) ? itemTag.tags[0] : itemTag.tags;
          return tag?.name ?? null;
        })
        .filter((name): name is string => name !== null);

      return {
        id: row.id,
        title: row.title,
        status: row.status,
        rating: row.rating,
        priority: row.priority,
        subtypeName: subtype?.name ?? "",
        tags,
        coverUrl,
      };
    }),
  );
}

// Item detail page (issue #13). Every field from plan.md §3 plus the two
// structural relations (Links, Attachments) the detail page also renders.
//
// ItemTag carries `id` alongside `name` (unlike LibraryItem's bare
// `tags: string[]` above) -- issue #17's detach control needs a tag_id to
// act on, which a plain name string can't provide. getLibraryItems/
// TagChips's read-only Card/List views have no such need and stay
// unchanged.
export interface ItemTag {
  id: string;
  name: string;
}

export interface ItemLink {
  id: string;
  url: string;
  label: string | null;
}

export interface ItemAttachment {
  id: string;
  filename: string;
  mimeType: string;
  sizeBytes: number;
  // Resolved eagerly below, same pattern as coverUrl -- a signed URL with
  // `{ download: filename }` baked in (issue #21's Constraints), so a plain
  // <a href> download saves under the real filename rather than the
  // opaque {attachment_id} storage path segment. Null only if signing
  // itself failed (transient Storage error), never as a sentinel for "no
  // attachment" -- every item_attachments row gets one.
  downloadUrl: string | null;
}

export interface ItemDetail {
  id: string;
  title: string;
  status: ItemStatus;
  rating: number | null;
  priority: PriorityLevel | null;
  notes: string | null;
  review: string | null;
  createdAt: string;
  completedAt: string | null;
  categoryId: string;
  subtypeId: string;
  subtypeName: string;
  tags: ItemTag[];
  coverUrl: string | null;
  links: ItemLink[];
  attachments: ItemAttachment[];
}

// Scoped to both `categoryId` (catches a URL whose `[category]` slug
// doesn't match the item's real category) and RLS's implicit `user_id =
// auth.uid()` (catches another user's item -- already indistinguishable
// from "doesn't exist", by design), plus `deleted_at IS NULL` (catches a
// soft-deleted item). A malformed-UUID `itemId` makes Postgres return a
// query error (invalid input syntax, not a thrown JS exception -- postgrest-
// js never throws for a query-level error) rather than data; that and every
// other case above all resolve to a `null` return here, so the route's
// `notFound()` call can't distinguish any of them. Reuses the same signed-
// URL-for-cover pattern and defensive embedded-resource normalization as
// getLibraryItems above, in one query per relation (no per-row N+1).
export async function getItemDetail(
  categoryId: string,
  itemId: string,
): Promise<ItemDetail | null> {
  const supabase = await createClient();

  const { data, error } = await supabase
    .from("items")
    .select(
      `
      id,
      title,
      status,
      rating,
      priority,
      notes,
      review,
      created_at,
      completed_at,
      category_id,
      subtype_id,
      subtypes ( name ),
      item_tags ( tags ( id, name ) ),
      item_images ( storage_path, is_cover ),
      item_links ( id, url, label ),
      item_attachments ( id, filename, mime_type, size_bytes, storage_path )
    `,
    )
    .eq("id", itemId)
    .eq("category_id", categoryId)
    .is("deleted_at", null)
    // Links display in insertion order (issue #20's acceptance criteria) --
    // without this the embedded item_links resource had no explicit order
    // and relied on whatever order Postgres/PostgREST happened to return.
    .order("created_at", { referencedTable: "item_links", ascending: true })
    .maybeSingle();

  if (error || !data) {
    if (error) {
      // A malformed-UUID itemId lands here too -- logged like any other
      // transient read error, but still resolved to `null` (not-found)
      // below rather than being surfaced as a 500/unhandled error.
      console.error("Failed to load item detail:", error.message);
    }
    return null;
  }

  const subtype = Array.isArray(data.subtypes) ? data.subtypes[0] : data.subtypes;
  const images = Array.isArray(data.item_images) ? data.item_images : [];
  const coverImage = images.find((image) => image.is_cover);

  let coverUrl: string | null = null;
  if (coverImage) {
    const { data: signed } = await supabase.storage
      .from("covers")
      .createSignedUrl(coverImage.storage_path, COVER_SIGNED_URL_TTL_SECONDS);
    coverUrl = signed?.signedUrl ?? null;
  }

  const tagRows = Array.isArray(data.item_tags) ? data.item_tags : [];
  const tags = tagRows
    .map((itemTag) => {
      const tag = Array.isArray(itemTag.tags) ? itemTag.tags[0] : itemTag.tags;
      return tag ? { id: tag.id, name: tag.name } : null;
    })
    .filter((tag): tag is ItemTag => tag !== null);

  const links = Array.isArray(data.item_links) ? data.item_links : [];
  const attachmentRows = Array.isArray(data.item_attachments) ? data.item_attachments : [];

  // Signed download URLs resolved eagerly, one per attachment, same
  // per-request (never cached) reasoning as coverUrl above -- the
  // `attachments` bucket is private/path-scoped too. `{ download: filename }`
  // is what makes the browser save under the real filename instead of the
  // opaque {attachment_id} path segment (issue #21's Constraints).
  const attachments = await Promise.all(
    attachmentRows.map(async (attachment) => {
      const { data: signed } = await supabase.storage
        .from("attachments")
        .createSignedUrl(attachment.storage_path, COVER_SIGNED_URL_TTL_SECONDS, {
          download: attachment.filename,
        });
      return {
        id: attachment.id,
        filename: attachment.filename,
        mimeType: attachment.mime_type,
        sizeBytes: attachment.size_bytes,
        downloadUrl: signed?.signedUrl ?? null,
      };
    }),
  );

  return {
    id: data.id,
    title: data.title,
    status: data.status,
    rating: data.rating,
    priority: data.priority,
    notes: data.notes,
    review: data.review,
    createdAt: data.created_at,
    completedAt: data.completed_at,
    categoryId: data.category_id,
    subtypeId: data.subtype_id,
    subtypeName: subtype?.name ?? "",
    tags,
    coverUrl,
    links: links.map((link) => ({ id: link.id, url: link.url, label: link.label })),
    attachments,
  };
}
